services:
  postgres:
    image: postgres:16

    container_name: railpulse-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: railpulse
      POSTGRES_PASSWORD: railpulse
      POSTGRES_DB: railpulse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: